
import { ProjectFormValues } from "./projectFormSchema";

export const getDefaultValues = (): Partial<ProjectFormValues> => ({
  projectName: "",
  projectType: "Residential",
  projectDescription: "",
  expectedStartDate: "",
  targetCompletionDate: "",
  siteAddress: "",
  plotDimensions: 0,
  soilType: "",
  siteAccessibility: "",
  existingInfrastructure: [],
  builtUpArea: 1000,
  numberOfFloors: 1,
  floorHeight: 10,
  constructionType: "RCC Frame Structure",
  architecturalStyle: "",
  foundationType: "Isolated Footing",
  structuralSystem: "",
  roofType: "",
  wallThickness: 9,
  columnSpecifications: "12x18 RCC columns, Grade of concrete M25",
  budgetRange: 0,
  qualityStandards: "",
  specialRequirements: "",
  sustainabilityGoals: [],
  endUsePurpose: "",
  localBuildingCode: "",
  permitStatus: "",
  environmentalClearance: false,
  fireSafetyRequirements: [],
  accessibilityCompliance: false,
  workforceAvailability: "",
  equipmentRequirements: [],
  materialPreferences: "",
  timelineConstraints: 0,
  budgetConstraints: 0,
  // New default values
  soilBearingCapacity: 200,
  waterTableLevel: 0,
  siteAccess: "Good",
  existingUtilities: [],
  climateZone: "Moderate",
  seismicZone: "Zone II",
  externalWallThickness: 230,
  internalWallThickness: 115,
  floorToFloorHeight: 3000,
  structuralGradeConcrete: "M20",
  steelGrade: "Fe415",
  fireNOCRequired: false,
  seismicDesignRequired: true,
  accessibilityFeatures: false,
  siteSafetyLevel: "Standard",
  totalElectricalLoad: 0,
  numberOfLightPoints: 0,
  numberOfPowerPoints: 0,
  acType: "",
  totalACTonnage: 0,
  numberOfBathrooms: 0,
  numberOfKitchens: 0,
  waterTankCapacity: 1000,
  fireSafetyRequired: false,
  constructionQualityGrade: "Standard",
  brickType: "Common Burnt Clay",
  cementType: "OPC 43",
  tileQuality: "",
  paintType: "",
  windowMaterial: "UPVC",
  sanitaryWareQuality: "",
  concreteTestingFrequency: "Standard",
  steelTestingRequired: true,
  thirdPartyInspection: false,
  qualityAssuranceLevel: "Standard",
  projectLocationState: "Karnataka",
  projectLocationCity: "Bangalore",
  distanceFromSupplierHub: 50,
  localLaborAvailability: "",
  monsoonImpact: "Moderate",
  bimIntegrationRequired: false,
  erpIntegration: false,
  realTimePricingRequired: true,
  automatedProcurement: false,
  preferredSuppliers: [],
  bulkPurchasePreference: true,
  deliveryTimeline: "Standard",
  paymentTermsPreference: "",
  greenBuildingCertification: "",
  sustainableMaterialsPreference: false,
  carbonFootprintTracking: false,
  wasteManagementPlan: false,
});
