// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://sqzrhhcdbhbwslmwjdjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxenJoaGNkYmhid3NsbXdqZGpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5Mjk4MjMsImV4cCI6MjA2NTUwNTgyM30.zi0dnA-z6vzWGrZHHIa74EZtxopTa7K9EHj0XRYHgls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);